apiVersion: v1
kind: Service
metadata:
  name: devops-project
spec:
  type: NodePort
  selector:
    app: devops-project
  ports:
    - name: devops-project
      protocol: "TCP"
      port: 3006
      targetPort: 3006