---
- hosts: gitlab_server
  # Run commands as root
  become: true
  # Roles to be executed on these hosts
  roles:
  - role: nodejs/install
    tags: install

  - role: redis/install
    tags: install

  - role: healthchecks/check
    tags: check